project_name: podump

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    # Ensure the binary is named correctly for kubectl plugin support
    binary: kubectl-podump
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # Use format_overrides for Windows to use zip instead of tar.gz
    format_overrides:
      - goos: windows
        format: zip
    # New way to handle replacements (mapping OS/Arch names)
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
